export const enum HintType {
  // INITIAL_VALUE,

  // easy
  NAKED_SINGLE,       // 0
  HIDDEN_SINGLE_ROW,
  HIDDEN_SINGLE_COL,
  HIDDEN_SINGLE_BOX,

  // medium
  NAKED_PAIRS_ROW,    // 4
  NAKED_PAIRS_COL,
  NAKED_PAIRS_BOX,
  POINTING_ROW,
  POINTING_COL,       // 8
  ROW_BOX_REDUCTION,
  COL_BOX_REDUCTION,

  // hard
  NAKED_TRIPLES_ROW,
  NAKED_TRIPLES_COL,  // 12
  NAKED_TRIPLES_BOX,

  HIDDEN_PAIRS_ROW,
  HIDDEN_PAIRS_COL,
  HIDDEN_PAIRS_BOX,   // 16

  NAKED_QUADS_ROW,
  NAKED_QUADS_COL,
  NAKED_QUADS_BOX,

  HIDDEN_TRIPLES_ROW, // 20
  HIDDEN_TRIPLES_COL,
  HIDDEN_TRIPLES_BOX,

  HIDDEN_QUADS_ROW,
  HIDDEN_QUADS_COL,   // 24
  HIDDEN_QUADS_BOX,

  // hardest
  GUESS               // 26
}
